// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHdgv9fP9WDJWSnVrPxEsyWOsritnj1dw',
    appId: '1:776830769279:web:6225211732b00c4c81074a',
    messagingSenderId: '776830769279',
    projectId: 'muraqib-6c183',
    authDomain: 'muraqib-6c183.firebaseapp.com',
    storageBucket: 'muraqib-6c183.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSyZ4wb0WzInisswaef7t4EwL9PmjzxLA',
    appId: '1:776830769279:android:a83d82fca29c34e381074a',
    messagingSenderId: '776830769279',
    projectId: 'muraqib-6c183',
    storageBucket: 'muraqib-6c183.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdmBo3qNij7lwY7b01SjKueIr8p03SG-I',
    appId: '1:776830769279:ios:3da5a45778d6b61e81074a',
    messagingSenderId: '776830769279',
    projectId: 'muraqib-6c183',
    storageBucket: 'muraqib-6c183.firebasestorage.app',
    iosBundleId: 'com.example.muraqib',
  );
}
